# playbooks/playbook.yml
- hosts: all
  tasks:
    - name: Create a text file in /tmp
      copy:
        content: "Playbook executed at {{ ansible_date_time.iso8601 }}"
        dest: /tmp/ansible_run.txt
